### ISSUE TITLE
need to add `trusted-users` options in `/etc/nix/nix.conf` for home-manager users

### ISSUE THREAD

**Issue by junyi-hou** [jonascarpay/declarative-cachix#2]
For people who do not use `nixOS`, I need to run
`sudo echo "trusted-users = $(whoami)" >> /etc/nix/nix.conf` to enable cacheix substitution and public key defined in `~/.config/nix/nix.conf`.

Also, it would be good to include a warning on the security issues associated with this (as indicated in the manual [here](https://nixos.org/manual/nix/stable/#ssec-multi-user))

**Comment by jonascarpay** [comment]
I added note and a link to this issue to this issue in the README.

Note that this also applies to people who run NixOS, but in that case you just add your own username to the `nix.trustedUsers` system option.

**Comment by junyi-hou** [comment]
Thanks!
